201805/the-path-to-service-mesh.md

initial commit of the-path-to-service-mesh

---

201806/containers-service-mesh-and-api-gateways-it-starts-at-the-edge.md

containers-service-mesh-and-api-gateways-it-starts-at-the-edge.md

---

201806/Istio-is-not-just-for-Microservices-Secure-your-Kubernetes-services-using-Istio-Service-Mesh.md

翻译的文档的 Issue 编号是：Istio is not just for Microservices: Secure your Kubernetes services using Istio Service Mesh #6

Istio is not just for Microservices: Secure your Kubernetes services using Istio Service Mesh #6

---

201807/designing-a-rate-limiting-service-for-ambassador-part-4.md

Part 4: Designing a Rate Limiting Service for Ambassador #33

---

201807/distributed-tracing-istio-and-your-applications.md

distributed-tracing-istio-and-your-applications.md #52

---

201808/Istio-service-mesh-tech-boosts-Kubernetes-work-with-trade-offs.md

close #50
翻译的文档的 Issue 编号是：#50

feat(trade-offs-istio-kubernetes): close #50

---

201808/why-you-should-care-about-istio-gateways.md

add why-you-should-care-about-istio-gateways.md

---

201808/google-istio-bigger-kubernetes-serverless.md
201808/securing-ingress-services-in-istio-with-lets-encrypt-on-kubernetes.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/82

google-istio-bigger-kubernetes-serverless

---

201808/Cilium1.2-DNS-Security -Policies-EKS-Support-ClusterMesh-kube-router-integration.md

Cilium1.2-DNS-Security -Policies-EKS-Support-ClusterMesh-kube-router-integration

---

201809/increasing-security-with-a-service-mesh-Christian-Posta-Explores-the-Capabilities-of-Istio.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/96

Increasing Security with a Service Mesh

---

201809/istio-service-mesh-interview-harrington.md

close #101
add
翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/101

feat(istio-service-mesh-interview-harrington): close #101

---

201809/xds-protocol.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/109

add xds-protocol.md

---

201810/Manipulating Istio and other Custom Kubernetes Resources in Golang.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/130

翻译的文档的 Issue 编号是：#130

---

201810/raw-tcp-traffic-shaping-with-Istio.md
201810/raw-tcp-traffic-shaping-with-istio-1.1.0.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/134
NOTE：
文章标题shaping with 意为“塑造、加工”，修饰“流量”并不合适，故翻译为“控制”；
文章中TCP ECHO Server，server在此处翻译为服务端、服务器都不贴切，故翻译为服务。

Translation: Raw TCP Traffic Shaping with Istio 1.1.0

---

201810/myth-cloud-native-portability.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/126

Translation:  The Myth of Cloud-Native Portabilit

---

201810/how-to-map-cloud-native-workloads-to-kubernetes-controllers.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/145

Translation: How to Map Cloud Native Workloads to Kubernetes Controllers

---

201811/sre-resiliency-bolt-on-sidecar-rate-limiting-with-envoy-sidecar.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/144

Translation: SRE: Resiliency: Bolt on Rate Limiting using Envoy

---

201811/microservices-monitoring-with-envoy-service-mesh-prometheus-grafana.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/154

Microservices monitoring with Envoy service mesh, Prometheus & Grafana

---

201811/transcoding-grpc-to-http-json-using-envoy.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/163

Translation: Transcoding gRPC to HTTP/JSON using Envoy 

---

201811/istio-is-it-a-bird-microgateway-blog-series-part-4.md
201811/istio-what-happens-when-control-plane-is-down.md

Translation: What happens when control plane is down? 

---

201811/service-mesh-with-envoy-101.md

Translation: Service Mesh with Envoy 101

---

201811/istio-routing-basics.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/153

Translation: Istio Routing Basics 

---

201812/Serverless-Jenkins-with-Jenkins-X.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/133

 Serverless-Jenkins-with-Jenkins-X

---

201812/distributed-tracing-with-envoy-service-mesh-jaeger.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/149
1. 原文笔误upto改为up to ( it is upto the services to forward the generated headers to outgoing requests. )
2. 原文只贴了service b的代码，译者粘贴了服务c的代码以保证完整性。

Translation: Distributed Tracing with Envoy Service Mesh & Jaeger

---

201901/envoy-and-grpc-web-a-fresh-new-alternative-to-rest.md

Translation: Envoy and gRPC-Web: a fresh new alternative to REST

---

201902/cilium-1.4.md

add
翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/200
close #200

Translation: cilium-14

---

201901/istio-kubernetes-service-mesh.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/159

Translation: Istio: The Enterprise Upgrade Path to Microservices

---

201902/knative-whittling-down-the-code.md

Translation: knative-whittling-down-the-code

---

201902/guidance-for-building-a-control-plane-to-manage-envoy-proxy-at-the-edge-as-a-gateway-or-in-a-mesh.md

close #209
翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/209

feat（envoy control plane guidance）

---

201903/application-metrics-in-istio.md

翻译的文档的 Issue 编号是：https://github.com/servicemesher/trans/issues/194

trans: application-metrics-in-istio

---

201903/hand-crafting-a-sidecar-proxy-like-istio.md

Add hand-crafting-a-sidecar-proxy-like-istio

---

201903/circuit-breaking-and-outlier-detection-in-istio.md

写了一篇文章用来演示如何为 Istio 网格中的服务配置熔断的连接数、请求数和异常检测。

circuit-breaking-and-outlier-detection-in-istio

---

201904/guidance-for-building-a-control-plane-for-envoy-part-4-build-for-extensibility.md

合并该 PR 前需要检查以下内容：
当所有以上问题都确定之后，可以由管理者合并 PR 并关闭关联 issue。

Translation: Guidance for Building a Control Plane for Envoy Part 4: Build for Extensibility

---

.mergify.yml

- 增加Mergify GitHub Apps小机器人 ，当有新的PR时，所有定义的Rules规则满足之后会自动合并PR。
- Rules规则可以自定义。
- [Mergify机器人](https://mergify.io/)
通过在根目录下放置对应的.mergify.yaml配置文件
- .mergify.yaml配置文件通过Rules 规则来配置Mergify机器人

feat:增加Mergify GitHub Apps小机器人

---

.circleci/config.yml
.spelling
mdl_style.rb
scripts/lint_site.sh

参考 istio.io 项目，添加一些基本自动化测试脚本，以后再逐步完善功能。
/cc @haiker2011 @rootsongjc

Add some basic ci scripts

---

.github/auto-comment.yml

添加关于 spell check 术语表的说明
/cc @haiker2011

add spell check instruction

---

.mergify.yml

Reverts servicemesher/trans#286

Revert "add build"

---

.spelling

请审校者在合并该 PR 前需要检查以下内容：
当所有以上问题都确定之后，可以由管理者合并 PR 并关闭关联 issue。

Add words into glossary

---

README.md

- 添加文章线索和文档提交到 [webiste](https://github.com/servicemesher/website)

添加文章线索和文档提交到website

---

.mergify.yml

- label!=do-not-merge
- label!=WIP

Feat: add label filter

---

mdl_style.rb

- 添加ruby rule MD010，去掉对markdown代码块中的制表符检查

feat: add ruby rule MD010

---

mdl_style.rb

请审校者在合并该 PR 前需要检查以下内容：
当所有以上问题都确定之后，可以由管理者合并 PR 并关闭关联 issue。

exclude rule 36 & 10
